### PR TITLE
Enhanced documentation on Settings and Settings-Editor

### PR DESCRIPTION
**Pull request by hoppfrosch**
* Enhanced documentation within Settings.html and Ini.html 
* Set Links to Settings.html and Ini.html throughout documentation

### CODE REVIEW

**Comment by aviaryan** [comment]
There looks to be some conflict in the FAQ.html file. Your previous PR #64 also had it. Can you fix this please ?

**Comment by hoppfrosch** [comment]
Sorry for the late answer and solution - was quite busy recently

**Comment by hoppfrosch** [comment]
Sorry for the late answer and solution - was quite busy recently

**Comment by hoppfrosch** [comment]
Sorry for the late answer and solution - was quite busy recently

**Comment by hoppfrosch** [comment]
Sorry for the late answer and solution - was quite busy recently

**Comment by hoppfrosch** [comment]
Sorry for the late answer and solution - was quite busy recently

**Comment by aviaryan** [comment]
Thanks. There's one small issue I see in shortcuts.html. The [line 130](https://github.com/aviaryan/Clipjump/pull/65/files#diff-33fdcd410e0ad20fb07708ef22ea9aeaL130) has link address as `*.htm` which is not present.

**Comment by hoppfrosch** [comment]
Strange - I haven't had the wrong link on my local branch. I do not understand where the discrepancy between my local branch and the contents of the pull requests is coming from ... Anyway I fixed it. 

I have to investigate and understand this behaviour locally to get higher quality pull requests in future.

**Comment by hoppfrosch** [comment]
Strange - I haven't had the wrong link on my local branch. I do not understand where the discrepancy between my local branch and the contents of the pull requests is coming from ... Anyway I fixed it. 

I have to investigate and understand this behaviour locally to get higher quality pull requests in future.

**Comment by hoppfrosch** [comment]
Strange - I haven't had the wrong link on my local branch. I do not understand where the discrepancy between my local branch and the contents of the pull requests is coming from ... Anyway I fixed it. 

I have to investigate and understand this behaviour locally to get higher quality pull requests in future.

**Pull request merged**
